{% set version = '0.2.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tilegramsr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tilegramsR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tilegramsR/tilegramsR_{{ version }}.tar.gz
  sha256: 22ee5ec89158e7ad366e9e357e8ec6dde22cfd95fa4395323d1f3df8e8f69685

build:
  merge_build_host: True  # [win]
  number: 5
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-sf
    - r-sp
  run:
    - r-base
    - r-sf
    - r-sp

test:
  commands:
    - $R -e "library('tilegramsR')"           # [not win]
    - "\"%R%\" -e \"library('tilegramsR')\""  # [win]

about:
  home: https://github.com/bhaskarvk/tilegramsR
  license: MIT
  summary: R spatial objects for Tilegrams. Tilegrams are tiled maps where the region size is
    proportional to the certain characteristics of the dataset.
  license_family: MIT
  license_file: 
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: tilegramsR
# Type: Package
# Title: R Spatial Data for Tilegrams
# Version: 0.2.0
# Authors@R: person("Bhaskar", "Karambelkar", email = "bhaskarvk@gmail.com", role = c("aut", "cre"))
# Description: R spatial objects for Tilegrams. Tilegrams are tiled maps where the region size is proportional to the certain characteristics of the dataset.
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: true
# Depends: R (>= 3.1.0), sf
# Imports: sp
# Suggests: dplyr, tidyr, knitr, rmarkdown, leaflet (>= 1.1.0),
# VignetteBuilder: knitr
# URL: https://github.com/bhaskarvk/tilegramsR
# BugReports: https://github.com/bhaskarvk/tilegramsR/issues
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-03-29 17:17:22 UTC; user001
# Author: Bhaskar Karambelkar [aut, cre]
# Maintainer: Bhaskar Karambelkar <bhaskarvk@gmail.com>
# Repository: CRAN
# Date/Publication: 2017-03-29 17:43:16 UTC
